# application: myProject
# version: 0-1
runtime: go
api_version: go1

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css))$
  static_files: build/\1
  upload: build/.*\.(gif|png|jpg|ico|js|css)$

- url: /.*
  script: _go_app